services:
  - type: web
    name: laravel-synchrove
    runtime: docker
    plan: free
    region: ohio
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel.synchrove.com
      - key: NODE_VERSION
        value: 20
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_KEY
        sync: false # You will paste your base64 key manually in the Render dashboard
      - key: DATABASE_URL
        fromDatabase:
          name: lilus_kitchen
          property: connectionString

databases:
  - name: lilus_kitchen
    plan: free
    region: ohio
