services:
  - type: web
    name: lilus-kitchen
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: docker/Dockerfile.render
    dockerContext: .
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://lilus.synchrove.com
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: lilus_kitchen
          property: connectionString

databases:
  - name: lilus_kitchen
    plan: free
    region: singapore
